#server:
#  error:
#    include-stacktrace: on_param

spring:
  datasource:
    username: sa
    password: sa
    hikari:
      jdbc-url: "jdbc:h2:./taskDB"
  h2:
    console:
      enabled: true
      path: /h2console/
      settings:
        web-allow-others: true
  jpa:
    show-sql: true

logging:
  level:
    root: info
    web: debug