server:
  port: ${PORT:5001}

base-url: /

spring:
  application:
    name: TaskTracker
  liquibase:
    change-log: classpath:db/changelog/db.changelog-master.yml
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  jpa:
    hibernate:
      ddl-auto: create-drop