server:
  error:
    include-stacktrace: never

spring:
  devtools:
    livereload:
      enabled: false
    restart:
      enabled: false
  jpa:
    show-sql: false
  datasource:
    usernam: ${PGUSER}
    password: ${PGPASSWORD}
    url: ${DATABASE_URL}
#    username: ""
#    password: ""
#    url: "jdbc:h2:./taskDB"s