server:
  error:
    include-stacktrace: on_param

spring:
  datasource:
    username: ""
    password: ""
    url: "jdbc:h2:./taskDB"
#  h2:
#    console:
#      enabled: true
#      path: /h2console/
#      settings:
#        web-allow-others: true
  jpa:
    show-sql: true

logging:
  level:
    web: debug
    root: info

#springdoc:
#  swagger-ui:
#    path: "swagger-ui1.html"